import runpy
import sys
from pathlib import Path
from types import TracebackType
from typing import TYPE_CHECKING, Any, ClassVar, Self, Type

from ninja import Writer

from bob.constants import (
    BOB_BUILDDIR_SUBDIRECTORY,
    get_build_ninja_path,
    get_compdb_ninja_path,
    get_configs_path,
    get_used_configs_path,
)

if TYPE_CHECKING:
    from bob.api.scope import Scope


class Context:
    _CURRENT: ClassVar[None | Self] = None

    def __init__(self, builddir: Path, bobfile: Path, configs: dict[str, str]):
        from bob.api.rule import FileTarget, PhonyTarget, RuleInput

        self.builddir = builddir
        self.bobfile = bobfile
        self.srcdir = Path(".")
        self.configs = configs
        self.used_configs: set[str] = set()
        self.writer: None | Writer = None
        self.compdb_writer: None | Writer = None
        self.configure_implicit_dependencies: set[RuleInput.Type] = {
            FileTarget(get_configs_path(builddir))
        }
        self.variables: dict[str, Any] = {}
        self.imports: None | dict[str, Any] = None
        self.exports: dict[str, Any] = {}
        self.always: PhonyTarget | None = None
        self.scopes: list[Scope] = []
        self.track_scopes = True

        self.current_build_subdir = Path(".")
        self.current_src_subdir = bobfile.parent

    def __enter__(self) -> Self:
        assert Context._CURRENT is None

        (self.builddir / BOB_BUILDDIR_SUBDIRECTORY).mkdir(parents=True, exist_ok=True)

        self.writer = Writer(
            open(get_build_ninja_path(self.builddir), "w"),  # type: ignore[arg-type] # ty: ignore[invalid-argument-type]
            width=999999,
        )
        self.compdb_writer = Writer(
            open(get_compdb_ninja_path(self.builddir), "w"),  # type: ignore[arg-type] # ty: ignore[invalid-argument-type]
            width=999999,
        )

        self.writer.comment("This file was automatically generated by Bob.")
        self.writer.variable("builddir", str(self.builddir / BOB_BUILDDIR_SUBDIRECTORY))

        Context._CURRENT = self

        from bob.api.rule import phony

        self.always = phony(str(self.builddir / BOB_BUILDDIR_SUBDIRECTORY / "always"))

        self.writer.newline()

        return self

    def __exit__(
        self,
        exc_type: None | Type[BaseException],
        exc: None | BaseException,
        tb: None | TracebackType,
    ) -> None:
        from bob.api.rule import Rule, RuleInput

        Rule(
            "FORCE_COLOR=1 $bobbin configure --use-current-configs -f $bobfile",
            description="CONFIGURE",
            generator=True,
            pool="console",
        ).build(
            str(get_build_ninja_path(self.builddir).relative_to(self.builddir)),
            implicit=sorted(
                self.configure_implicit_dependencies,
                key=lambda i: RuleInput.resolve(
                    i, path_only=True, convert_to_string=True
                ),
            ),
            variables={
                "bobbin": f"{sys.executable} -m bob",
                "bobfile": str(self.bobfile),
            },
        )

        get_used_configs_path(self.builddir).write_text(
            "\n".join(sorted(self.used_configs))
        )

        assert self.writer is not None
        assert self.compdb_writer is not None
        self.writer.close()
        self.writer = None
        self.compdb_writer.close()
        self.compdb_writer = None

        if exc is not None:
            get_build_ninja_path(self.builddir).unlink()
            get_compdb_ninja_path(self.builddir).unlink()

        assert Context._CURRENT is self
        Context._CURRENT = None

    @staticmethod
    def current() -> "Context":
        result = Context._CURRENT
        assert result is not None
        return result

    def evaluate(
        self,
        bobfile: Path,
        validate_configs: bool = True,
    ) -> None:
        if validate_configs:
            self.used_configs = set()

        self.configure_implicit_dependencies.add(bobfile)

        runpy.run_path(str(bobfile))

        assert self.track_scopes, (
            "An unclosed plugin scope was detected, this can cause a myriad of side-effects!"
        )

        if validate_configs:
            for key in self.configs:
                assert key in self.used_configs, f'Invalid config "{key}"'
