"""Bob configuration context."""

import importlib.machinery
import importlib.util
import sys
from pathlib import Path
from typing import (
    TYPE_CHECKING,
    Any,
    Dict,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    TypeVar,
    Union,
    overload,
)

from ninja.ninja_syntax import Writer

from bob.constants import BOB_BUILD_SUBDIR
from bob.core.targets import RootRelativePath

if TYPE_CHECKING:
    from bob.core.provider import Provider

T = TypeVar("T")


class Exports:
    def __init__(self, exports: Dict[str, Any]):
        self._exports = exports

    @overload
    def use(
        self,
        name: str,
        type: Type[T],
        optional: bool = False,
        default: Optional[T] = None,
    ) -> T: ...

    @overload
    def use(
        self, name: str, type: None = None, optional: bool = False, default: Any = None
    ) -> Any: ...

    def use(
        self,
        name: str,
        type: Optional[Type[T]] = None,
        optional: bool = False,
        default: Any = None,
    ) -> Union[T, Any]:
        """
        Get a specific export by its name.
        :param name: The name of the exported value.
        :param type: An optional class to verify the export is an instance of.
        :param optional: Succeed even if the export doesn't exist.
        :param default: Return this value if the export doesn't exist and `optional` is set.
        """

        if optional and name not in self._exports:
            return default

        result = self._exports[name]

        if type is not None and not isinstance(result, type):
            raise TypeError()

        return result


class BobContext:
    _instance: Optional["BobContext"] = None

    def __init__(
        self,
        builddir: Path,
        bobfile_path: Path,
        configs: Dict[str, str],
        build_ninja_path: Path,
        compdb_ninja_path: Path,
        bob_configs_path: Path,
        allow_build_outside_builddir=False,
    ) -> None:
        from bob.core.rule import PhonyTarget, Rule

        root = bobfile_path.parent
        self.root = root.resolve()
        self.builddir = RootRelativePath(builddir)
        self.build_ninja_path = RootRelativePath(build_ninja_path.relative_to(root))
        self.compdb_ninja_path = RootRelativePath(compdb_ninja_path.relative_to(root))
        self.bob_configs_path = RootRelativePath(bob_configs_path.relative_to(root))
        self.bobfile_path = bobfile_path
        self.configs = configs
        self.allow_build_outside_builddir = allow_build_outside_builddir

        self.writer: Optional[Writer] = None
        self.configure_implicit_dependencies: Optional[Set[RootRelativePath]] = None

        self.current_source_dir = RootRelativePath(".")
        self.current_build_dir = RootRelativePath(self.builddir)
        self.exports: Dict[str, Any] = {}
        self.provides: Dict[str, Any] = {}
        self.rules: List[Rule] = []
        self.providers: List["Provider"] = []
        self.always: Optional[PhonyTarget] = None
        self._backups: List[
            Tuple[
                RootRelativePath,
                RootRelativePath,
                Dict[str, str],
                Set[str],
                Dict[str, Any],
                Dict[str, Any],
                List[Rule],
                List[Provider],
            ]
        ] = []

        self.unused_configs = set(configs.keys())

        self.rule_index = 1
        self.shell_index = 1

    def __enter__(self) -> "BobContext":
        from bob.core.rule import phony

        self.build_ninja_path.resolve().parent.mkdir(parents=True, exist_ok=True)
        self.compdb_ninja_path.resolve().parent.mkdir(parents=True, exist_ok=True)

        self.writer = Writer(open(self.build_ninja_path.resolve(), "w"))  # ty:ignore[invalid-argument-type]
        self.compdb_writer = Writer(open(self.compdb_ninja_path.resolve(), "w"))  # ty:ignore[invalid-argument-type]
        self.configure_implicit_dependencies = set()
        self.configure_implicit_dependencies.add(self.bob_configs_path)

        self.writer.comment("This file was automatically generated by Bob.")
        self.writer.variable("builddir", str(self.builddir / BOB_BUILD_SUBDIR))
        self.writer.newline()

        self.compdb_writer.comment(
            "This file was automatically generated by Bob to create a compilation DB."
        )
        self.compdb_writer.newline()

        self.always = phony(str(self.builddir / BOB_BUILD_SUBDIR / "always"), inputs=[])

        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        from bob.core.rule import Rule

        build_ninja_name = self.build_ninja_path.resolve().relative_to(
            self.builddir.resolve()
        )

        assert self.configure_implicit_dependencies is not None
        assert self.writer is not None
        assert self.compdb_writer is not None

        Rule(
            "FORCE_COLOR=1 $bobbin configure --use-current-configs -f $bobfile",
            description="CONFIGURE",
            generator=True,
            pool="console",
        ).build(
            build_ninja_name,
            implicit=list(sorted(str(d) for d in self.configure_implicit_dependencies)),
            bobbin=[sys.executable, "-m", "bob"],
            bobfile=self.bobfile_path,
        )

        self.writer.close()
        self.writer = None
        self.compdb_writer.close()
        self.compdb_writer = None
        self.configure_implicit_dependencies = None

        if exc is not None:
            self.build_ninja_path.value.unlink(missing_ok=True)
            self.compdb_ninja_path.value.unlink(missing_ok=True)

        BobContext._instance = None

    @staticmethod
    def create(
        builddir: Path,
        bobfile_path: Path,
        configs: Dict[str, str],
        build_ninja_path: Path,
        compdb_ninja_path: Path,
        bob_configs_path: Path,
        allow_build_outside_builddir: bool,
    ) -> "BobContext":
        assert BobContext._instance is None

        context = BobContext(
            builddir,
            bobfile_path,
            configs,
            build_ninja_path=build_ninja_path,
            compdb_ninja_path=compdb_ninja_path,
            bob_configs_path=bob_configs_path,
            allow_build_outside_builddir=allow_build_outside_builddir,
        )

        BobContext._instance = context

        return context

    @staticmethod
    def get() -> "BobContext":
        assert BobContext._instance is not None

        return BobContext._instance

    def configure(self, bobfile_path: Union[None, Path, str] = None) -> None:
        assert self.configure_implicit_dependencies is not None

        if bobfile_path is None:
            bobfile_path = self.bobfile_path

        bobfile = RootRelativePath(bobfile_path)

        if not bobfile.is_file():
            raise FileNotFoundError(
                f"Can't configure, {bobfile.resolve()} doesn't exist!"
            )

        spec = importlib.util.spec_from_loader(
            "configure",
            importlib.machinery.SourceFileLoader("configure", str(bobfile)),
        )
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        self.configure_implicit_dependencies.add(bobfile)

    def _backup(self):
        self._backups.append(
            (
                self.current_source_dir,
                self.current_build_dir,
                self.configs.copy(),
                self.unused_configs.copy(),
                self.exports.copy(),
                self.provides.copy(),
                self.rules.copy(),
                self.providers.copy(),
            )
        )
        for rule in self.rules:
            rule._backup()
        for provider in self.providers:
            provider._backup()

    def _restore(self):
        (
            self.current_source_dir,
            self.current_build_dir,
            self.configs,
            self.unused_configs,
            self.exports,
            self.provides,
            self.rules,
            self.providers,
        ) = self._backups.pop()
        for rule in self.rules:
            rule._restore()
        for provider in self.providers:
            provider._restore()

    def get_exports(self) -> Exports:
        return Exports(self.exports)
