import runpy
import sys
from pathlib import Path
from typing import Any, Self

from ninja import Writer

from bob.constants import (
    BOB_BUILDDIR_SUBDIRECTORY,
    get_build_ninja_path,
    get_compdb_ninja_path,
)


class Context:
    _CURRENT: None | Self = None

    def __init__(self, builddir: Path):
        self.builddir = builddir
        self.writer: None | Writer = None
        self.compdb_writer: None | Writer = None
        self.configure_implicit_dependencies: set[Path] = set()
        self.variables: dict[str, Any] = {}
        self.bobfile: None | Path = None

    def __enter__(self) -> Self:
        assert Context._CURRENT is None

        (self.builddir / BOB_BUILDDIR_SUBDIRECTORY).mkdir(parents=True, exist_ok=True)

        self.writer = Writer(
            open(get_build_ninja_path(self.builddir), "w"),  # ty: ignore[invalid-argument-type]
        )
        self.compdb_writer = Writer(
            open(get_compdb_ninja_path(self.builddir), "w"),  # ty: ignore[invalid-argument-type]
        )

        self.writer.comment("This file was automatically generated by Bob.")
        self.writer.variable("builddir", str(self.builddir / BOB_BUILDDIR_SUBDIRECTORY))
        self.writer.newline()

        Context._CURRENT = self
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        from bob.api.rule import Rule

        Rule(
            "FORCE_COLOR=1 $bobbin configure -f $bobfile",
            description="CONFIGURE",
            generator=True,
            pool="console",
        ).build(
            str(get_build_ninja_path(self.builddir).relative_to(self.builddir)),
            implicit=list(sorted(str(d) for d in self.configure_implicit_dependencies)),
            variables={
                "bobbin": f"{sys.executable} -m bob",
                "bobfile": str(self.bobfile),
            },
        )

        assert self.writer is not None
        assert self.compdb_writer is not None
        self.writer.close()
        self.writer = None
        self.compdb_writer.close()
        self.compdb_writer = None

        if exc is not None:
            get_build_ninja_path(self.builddir).unlink()
            get_compdb_ninja_path(self.builddir).unlink()

        assert Context._CURRENT is self
        Context._CURRENT = None

    @staticmethod
    def current() -> "Context":
        result = Context._CURRENT
        assert result is not None
        return result

    def evaluate(self, bobfile: Path) -> None:
        if self.bobfile is None:
            self.bobfile = bobfile

        self.configure_implicit_dependencies.add(bobfile)
        runpy.run_path(str(bobfile))
